---

- name: stop postgres service
  sudo: yes
  ignore_errors: yes
  service: name={{postgres_service_name}} enabled=no state=stopped
  tags: uninstall

- name: remove postgres data directory
  file: path="{{postgres_data_dir}}" state=absent
  ignore_errors: yes
  tags: uninstall

- name: remove postgres logs directory
  file: path="{{postgres_data_dir}}" state=absent
  ignore_errors: yes
  tags: uninstall

- name: remove postgres service config
  file: path="/etc/systemd/system/{{postgres_service_name}}.service" state=absent
  ignore_errors: yes
  tags: uninstall
